language: node_js
sudo: false
node_js:
- 'lts/*'
after_success:
- ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  skip_cleanup: true
  api_key:
    secure: cFYORov9PIQf5AHRzr0nskLjMuI/3+P193OMV412Q/+/zvM6Z0WHTnfDHqb8RYolCJQiZDFMXrMu1qC+2LrmrgmR5tQ/PrhrKPPlL8mrcOmEMuPAhbkh6A0a7thuUI2itGBBIXeIxExNdO/IArhaFh5xxo5Dksx4Kvk8rJ+3hF4=
  on:
    tags: true
    repo: noflo/noflo
