# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: 8

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g grunt-cli
  - npm install
  - npm build

build: off
  
test_script:
  - node --version
  - npm --version
  - cmd: grunt test:nodejs --no-color
